export const PRODUCT_QUERY_INFO = 'product/PRODUCT_QUERY_INFO';
export const CREATE_ORDER = 'order/CREATE_ORDER';
export const CREATE_RESEVER_ORDER = 'order/CREATE_RESEVER_ORDER';
export const ORDER_ACTION_UPLOAD_DOWN = 'order/ORDER_ACTION_UPLOAD_DOWN';
