
// 新增产品.
export const PRODUCT_PUBLISH_INFO = 'user/PUBLISHPRODUCT';
export const PRODUCT_QUERY_INFO = 'user/PRODUCT_QUERY_INFO';

// 发布活动.
export const ACTIVE_CREATE_ACTION = 'action/ACTIVE_CREATE_ACTION';
export const ACTIVE_INFO_ACTION = 'action/ACTIVE_INFO_ACTION';
export const ACTIVE_OWNER_ACTION = 'action/ACTIVE_OWNER_ACTION';
export const ACTIVE_CLOSE_ACTION = 'action/ACTIVE_CLOSE_ACTION';

// 上传图片
export const UPLOAD_FILE_IMAGE = 'UPLOAD_FILE_IMAGE';
export const ACTION_UPLOAD_CONFIG = 'action/ACTION_UPLOAD_CONFIG';
export const ACTION_UPLOAD_DOWN = 'action/ACTION_UPLOAD_DOWN';

