export const ACTION_PRODUCT_LIST='product/ACTION_PRODUCT_LIST';

export const ACTION_PRODUCT_CREATE = 'product/ACTION_PRODUCT_CREATE';

export const ACTION_UPLOAD_CONFIG = 'action/ACTION_UPLOAD_CONFIG';

export const ACTION_UPLOAD_DOWN = 'action/ACTION_UPLOAD_DOWN';

export const ACTIVE_INFO_ACTION = 'action/ACTIVE_INFO_ACTION';

export const ACTION_PRODUCT_CATEOGRY = 'action/ACTION_PRODUCT_CATEOGRY';

export const ACTION_SELECT_PRODUCT = 'action/ACTION_SELECT_PRODUCT';

export const WX_USER_LOGIN = 'user/WX_USER_LOGIN';


export const UPDATE_USER_INFO = 'user/UPDATE_USER_INFO';

